stages:
  data_cleaning:

    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw
    - src/data/data_cleaning.py
    params:
    - data_cleaning.test_size
    outs:
    - data/cleaned

  feature_engineering:

    cmd: python src/features/feature_engineering.py
    deps:
    - data/cleaned
    - src/features/feature_engineering.py
    outs:
    - data/processed
    - models/processor.pkl

  model_building:

    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - train.Random_Forest
    - train.LGBM
    outs:
    - models/final_model.pkl
    - models/stacking_regressor.pkl
    - models/stacking_transformer.pkl

  model_evaluation:

    cmd: python src/model/model_evaluation.py
    deps:
    - models/final_model.pkl
    - data/processed
    - src/model/model_evaluation.py
    metrics:
    - reports/eval_metrics.json
    outs:
    - reports/models_info.json

  model_registration:

    cmd: python src/model/model_register.py
    deps:
    - reports/models_info.json
    - src/model/model_register.py
    
    


