data_cleaning:
  test_size: 0.20

train:
  Random_Forest:
    n_estimators: 908
    max_depth: 18
    min_samples_split: 7
    min_samples_leaf: 20
    max_features: Null
    bootstrap: True
    random_state: 41

  LGBM:
    max_depth: 20
    learning_rate: 0.64445579820183
    subsample: 0.554662572718122
    min_child_weight: 8
    min_split_gain: 0.200905822105394
    reg_lambda: 10.798160523492442
    random_state: 41
